module.exports = [{
        id: 580,
        category: "bread",
        name: "WhiteBread",
        price: 0.5,
        quantity: 0,
        order_id: "dfgdsg345",
    },
    {
        id: 584,
        category: "bread",
        name: "BrownBread",
        price: 0.7,
        quantity: 0,
        order_id: "arertyr456",
    },
    {
        id: 585,
        category: "vegetables",
        name: "Cucumber",
        price: 0.4,
        quantity: 0,
        selected: false,
        order_id: "dfgdsg345",
    },
    {
        id: 587,
        category: "vegetables",
        name: "Letuce",
        price: 0.3,
        quantity: 0,
        order_id: "arertyr456",
        selected: false,
    },
    {
        id: 588,
        category: "vegetables",
        name: "Tomato",
        price: 0.5,
        quantity: 0,
        order_id: "dfgdsg345",
        selected: false,
    },
    {
        id: 589,
        category: "vegetables",
        name: "Onion",
        price: 0.5,
        quantity: 0,
        order_id: "dfgdsg345",
        selected: false,
    },
    {
        id: 590,
        category: "cheese",
        name: "Cheddar",
        price: 1.2,
        quantity: 0,
        order_id: "arertyr456",
    },
    {
        id: 591,
        category: "cheese",
        name: "YellowCheese",
        price: 1.1,
        quantity: 0,
        order_id: "dfgdsg345",
    },
    {
        id: 592,
        category: "meat",
        name: "Beef",
        price: 1.8,
        quantity: 0,
        order_id: "arertyr456",
    },
    {
        id: 593,
        category: "meat",
        name: "Chicken",
        price: 1.6,
        quantity: 0,
        order_id: "dfgdsg345",
    },
];