module.exports = [{
        id: 580,
        category: "bread",
        name: "WhiteBread",
        price: 0.5,
        quantity: 0,
        order_id: "dfgdsg345",
    },
    {
        id: 584,
        category: "bread",
        name: "BrownBread",
        price: 0.7,
        quantity: 0,
        order_id: "arertyr456",
    },
    {
        id: 585,
        category: "vegetables",
        name: "Cucumber",
        price: 0.4,
        quantity: 0,
        selected: false,
        order_id: "arertyr456",
    },
    {
        id: 500,
        category: "vegetables",
        name: "Onion",
        price: 0.5,
        quantity: 0,
        order_id: "dfgdsg345",
        selected: false,
    },
    {
        id: 587,
        category: "vegetables",
        name: "Letuce",
        price: 0.3,
        quantity: 0,
        order_id: "arertyr456",
        selected: false,
    },
    {
        id: 588,
        category: "vegetables",
        name: "Tomato",
        price: 0.5,
        quantity: 0,
        order_id: "dfgdsg345",
        selected: false,
    },
    {
        id: 589,
        category: "vegetables",
        name: "Onion",
        price: 0.5,
        quantity: 0,
        order_id: "dfgdsg345",
        selected: false,
    },
    {
        id: 590,
        category: "cheese",
        name: "Cheddar",
        price: 1.2,
        quantity: 0,
        order_id: "arertyr456",
    },
    {
        id: 591,
        category: "cheese",
        name: "YellowCheese",
        price: 1.1,
        quantity: 0,
        order_id: "dfgdsg345",
    },
    {
        id: 592,
        category: "meat",
        name: "Beef",
        price: 1.8,
        quantity: 0,
        order_id: "arertyr456",
    },
    {
        id: 593,
        category: "meat",
        name: "Chicken",
        price: 1.6,
        quantity: 0,
        order_id: "dfgdsg345",
    },

    {
        id: 785,
        category: "bread",
        name: "BrownBread",
        price: 0.7,
        quantity: 0,
        order_id: "gjs34654",
    },
    {
        id: 745,
        category: "vegetables",
        name: "Cucumber",
        price: 0.4,
        quantity: 0,
        selected: false,
        order_id: "gjs34654",
    },
    {
        id: 756,
        category: "vegetables",
        name: "Letuce",
        price: 0.3,
        quantity: 0,
        order_id: "gjs34654",
        selected: false,
    },
    {
        id: 789,
        category: "vegetables",
        name: "Tomato",
        price: 0.5,
        quantity: 0,
        order_id: "gjs34654",
        selected: false,
    },
    {
        id: 728,
        category: "cheese",
        name: "YellowCheese",
        price: 1.1,
        quantity: 0,
        order_id: "gjs34654",
    },
    {
        id: 711,
        category: "meat",
        name: "Beef",
        price: 1.8,
        quantity: 0,
        order_id: "gjs34654",
    },
    {
        id: 820,
        category: "bread",
        name: "WhiteBread",
        price: 0.5,
        quantity: 0,
        order_id: "certt6563ad",
    },
    {
        id: 897,
        category: "vegetables",
        name: "Onion",
        price: 0.5,
        quantity: 0,
        selected: false,
        order_id: "certt6563ad",
    },
    {
        id: 842,
        category: "vegetables",
        name: "Letuce",
        price: 0.3,
        quantity: 0,
        order_id: "certt6563ad",
        selected: false,
    },
    {
        id: 810,
        category: "vegetables",
        name: "Tomato",
        price: 0.5,
        quantity: 0,
        order_id: "certt6563ad",
        selected: false,
    },
    {
        id: 832,
        category: "cheese",
        name: "Cheddar",
        price: 1.2,
        quantity: 0,
        order_id: "certt6563ad",
    },
    {
        id: 822,
        category: "meat",
        name: "Chicken",
        price: 1.6,
        quantity: 0,
        order_id: "certt6563ad",
    },

    {
        id: 123,
        category: "bread",
        name: "WhiteBread",
        price: 0.5,
        quantity: 0,
        order_id: "ngdty43th",
    },
    {
        id: 111,
        category: "vegetables",
        name: "Onion",
        price: 0.5,
        quantity: 0,
        selected: false,
        order_id: "ngdty43th",
    },

    {
        id: 109,
        category: "cheese",
        name: "Cheddar",
        price: 1.2,
        quantity: 0,
        order_id: "ngdty43th",
    },
    {
        id: 189,
        category: "meat",
        name: "Chicken",
        price: 1.6,
        quantity: 0,
        order_id: "ngdty43th",
    },

    {
        id: 269,
        category: "bread",
        name: "BrownBread",
        price: 0.7,
        quantity: 0,
        order_id: "fhdsl34e",
    },
    {
        id: 248,
        category: "vegetables",
        name: "Onion",
        price: 0.5,
        quantity: 0,
        selected: false,
        order_id: "fhdsl34e",
    },
    {
        id: 226,
        category: "vegetables",
        name: "Cucumber",
        price: 0.5,
        quantity: 0,
        selected: false,
        order_id: "fhdsl34e",
    },

    {
        id: 201,
        category: "cheese",
        name: "Cheddar",
        price: 1.2,
        quantity: 0,
        order_id: "fhdsl34e",
    },
    {
        id: 249,
        category: "meat",
        name: "Beaf",
        price: 1.8,
        quantity: 0,
        order_id: "fhdsl34e",
    },

    {
        id: 302,
        category: "bread",
        name: "BrownBread",
        price: 0.7,
        quantity: 0,
        order_id: "htrytr372",
    },
    {
        id: 396,
        category: "vegetables",
        name: "Tomato",
        price: 0.5,
        quantity: 0,
        selected: false,
        order_id: "htrytr372",
    },

    {
        id: 318,
        category: "cheese",
        name: "Cheddar",
        price: 1.2,
        quantity: 0,
        order_id: "htrytr372",
    },
    {
        id: 379,
        category: "meat",
        name: "Beaf",
        price: 1.8,
        quantity: 0,
        order_id: "htrytr372",
    },
];