//const test =require('../assets/images/1.png')
module.exports = [{
        id: "dfgdsg345",
        name: "Crispy Burger",
        image: "../assets/images/1.png",
        orderPrice: 4.6,
        quantity: 0,
        image: "https://img.freepik.com/premium-photo/cheese-burger-with-onion-tomato-lettuce-bacon-white-background_499484-1161.jpg?w=2000",
        comment: "",
        progress: 100,
    },
    {
        id: "arertyr456",
        name: "Beef Burger",
        image: "https://i.pinimg.com/736x/92/61/ae/9261ae26f462f67153f08cfcdd786999.jpg",
        orderPrice: 4.4,
        quantity: 0,
        comment: "",
        progress: 100,
    },
    {
        id: "gjs34654",
        name: "Deluxe Burger",
        image: "https://media.istockphoto.com/id/922719112/photo/tasty-cheeseburger-on-white.jpg?s=612x612&w=0&k=20&c=4u8jaTq2I5Eg2BaBcWW6VIV9vUmgmKfLiwfGn_xQnwQ=",
        orderPrice: 4.8,
        quantity: 0,
        comment: "",
        progress: 100,
    },

    {
        id: "certt6563ad",
        name: "Healthy Burger",
        image: "https://img.freepik.com/premium-photo/chicken-burger-with-sauce-isolated-white-background_1339-152505.jpg?w=2000",
        orderPrice: 5.6,
        quantity: 0,
        comment: "",
        progress: 100,
    },

    {
        id: "ngdty43th",
        name: "Cheese Burger",
        image: "https://static.vecteezy.com/system/resources/previews/002/610/800/large_2x/chicken-hamburger-with-vegetables-isolated-on-white-background-free-photo.jpg",
        orderPrice: 3.8,
        quantity: 0,
        comment: "",
        progress: 100,
    },

    {
        id: "fhdsl34e",
        name: "Barbeque Burger",
        image: "https://media.istockphoto.com/id/1206323282/photo/juicy-hamburger-on-white-background.jpg?s=612x612&w=0&k=20&c=K0DxyiChLwewXcCy8aLjjOqkc8QXPgQMAW-vwRCzqG4=",
        orderPrice: 4.7,
        quantity: 0,
        comment: "",
        progress: 100,
    },

    {
        id: "htrytr372",
        name: "CheddarBurger",
        image: "https://thumbs.dreamstime.com/b/hamburger-sur-le-fond-blanc-54090128.jpg",
        orderPrice: 4.2,
        quantity: 0,
        comment: "",
        progress: 100,
    },
];